### ISSUE TITLE
Could not find file '...\schema.json'.

### ISSUE THREAD

**Issue by eferfolja** [JordanMarr/SqlHydra#1] opened 2021-05-24 07:44 UTC
First, let me say: 
great library and thanks for your hard work  :pray: Using it with Dapper.FSharp is awesome.

I am testing the library SqlHydra.SqlServer (following the readme), and I get the following error (in AdventureWorks.fs):
```
namespace rec globalmodule SqlServerGeneratorFailure =
    let (!CompilationError) =
        "Could not find file 'C:\dev\MyTest\schema.json'."
```

I suspected my connection string but... If (instead of using the Nuget package) I clone the repo and replace the `connection` in `myriad.toml` with my connection, everything works.

If is needed I can paste my configs (they are pretty basic as I am following the readme). But I guess there is something wrong with the nuget package.

**Comment by JordanMarr** [comment] 2021-05-24 08:17
Thank you for testing. 
Would it be possible to post a small reproduction solution to GitHub so that I can study it? 
Which OS are you running it on?

**Comment by JordanMarr** [comment] 2021-05-24 08:24
Another thing is that if you had to adjust the connection string after receiving an error, it could be that the build error in the output file is preventing subsequent runs from properly building, so you might want to try manually deleting the errored output file from the file system before rebuilding.

**Comment by JordanMarr** [comment] 2021-05-24 09:01
No need to upload a repro project - I was able to reproduce it with a brand new project. 
it is indeed a problem with the nuget package. 

Stayed tuned…

**Comment by eferfolja** [comment] 2021-05-24 09:31
I was just about to reply to you with a link to a repro project... Great that you could reproduce it.

Will stay tuned :wink:

**Comment by JordanMarr** [comment] 2021-05-25 17:53
I had an epiphany while fighting NuGet last night that this whole thing should just be a dotnet tool. 
https://twitter.com/jordan_n_marr/status/1397248838105174020?s=20

Closing this issue due to total rewrite. 😁

**Closed by JordanMarr** 2021-05-25 17:53 UTC
