### ISSUE TITLE
`deleteAll` failing with SqlHydra.Query 1.1.0

### ISSUE THREAD

**Issue by MangelMaxime** [JordanMarr/SqlHydra#46] opened 2022-12-30 10:50 UTC
Using the following code with SqlHydra.Query 1.1.0 result in an error at runtime:

```fs
module Tables =

    let encounterForms = table<dbo.EncounterForms>

    let! _ =
        deleteAsync (Shared ctx) {
            for _ in Tables.encounterForms do
                deleteAll
        }
```

```
System.NotImplementedException: The method or operation is not implemented.
   at SqlHydra.Query.QuotationVisitor.visit@10(FSharpExpr expr)
   at SqlHydra.Query.QuotationVisitor.visitFor[T](FSharpExpr`1 f)
   at SqlHydra.Query.DeleteBuilders.DeleteBuilder`1.For[T](QuerySource`1 state, FSharpExpr`1 forExpr)
   at Antidote.Server.Tests.Database.clean@57-1.Invoke(QueryContext _arg1) in /Users/mmangel/Workspaces/Github/Antidote-AI/antidote-apps/Server/Antidote.Server.Tests/Database.fs:line 73
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 510
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 112
```

Downgrading to SqlHydra 1.0.5 with the following code:

```fs
module Tables =

	let encounterForms = table<dbo.EncounterForms> |> inSchema (nameof dbo)

    let! _ =
        deleteAsync (Shared ctx) {
            for _ in Tables.encounterForms do
                deleteAll
        }
```

works.

**Comment by JordanMarr** [comment] 2022-12-30 11:37
Ok, I think that should be a simple fix.

**Comment by MangelMaxime** [comment] 2022-12-30 13:16
In case it helps here is the configuration file I am using:

```toml
[general]
connection = "Server=127.0.0.1,33300;Database=XXX;User Id=SA;Password=XXXXXXXX;TrustServerCertificate=True"
output = "Server/Antidote.Database/Dbos.fs"
namespace = "Antidote.Database"
cli_mutable = false
[readers]
reader_type = "Microsoft.Data.SqlClient.SqlDataReader"
[filters]
include = []
exclude = []
```

With `sqlhydra.sqlserver@1.1.1`

**Comment by JordanMarr** [comment] 2022-12-30 17:39
It seems to be caused by using the `_` assignment.

**Comment by JordanMarr** [comment] 2022-12-30 18:45
A fix has been pushed to the main branch that allows `_` to be used only for `DeleteBuilder` queries.

**Comment by MangelMaxime** [comment] 2022-12-31 10:58
Thank you @JordanMarr 

I never tough it would be because of the `_` 😅.

I will test it when released.

**Comment by JordanMarr** [comment] 2022-12-31 21:41
Previous versions always created queries using the fully qualified table and column names, but a recent update changed it so that everything uses table aliases named after the actual table binding.

For example, this query:

```F#
for p in dbo.Tables.Products do 
select p
``` 

will now use `p` as the table alias:

```sql
SELECT p.*
FROM dbo.Products AS p
```

This change makes the generated queries nicer, but more importantly, it allows for same table joins.
So that's what caused the odd bug!

SqlHydra.Query v1.1.1 is now released with the patch.

**Closed by JordanMarr** 2022-12-31 21:41 UTC

**Comment by MangelMaxime** [comment] 2023-01-01 09:27
The alias makes senses.

Fix is also working for my project thank you very much.
